name: Add Environment-Specific Branch Protection

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name (owner/repo)"
        required: true
      branch:
        description: "Branch name to apply protection"
        required: true
      environment:
        description: "Environment name to apply protection rules"
        required: true

jobs:
  set-environment-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Environment-Specific Branch Protection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f1)
          repo=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f2)
          branch="${{ github.event.inputs.branch }}"
          environment="${{ github.event.inputs.environment }}"

          # Update environment-specific protection rules
          curl -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$owner/$repo/environments/$environment \
            -d '{
              "wait_timer": 30,
              "reviewers": {
                "users": [],
                "teams": ["team-slug"]
              },
              "deployment_branch_policy": {
                "protected_branches": true,
                "custom_branch_policies": false
              },
              "allow_deployment_from": {
                "branches": ["'"$branch"'"]
              }
            }'

          echo "Environment-specific protection rules applied to branch $branch in environment $environment"
