name: Add Classic Branch Protection

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name (owner/repo)"
        required: true
      branch:
        description: "Branch name to apply protection"
        required: true

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Classic Branch Protection
        env:
          AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Parse inputs
          owner=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f1)
          repo=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f2)
          branch="${{ github.event.inputs.branch }}"

          # Define branch protection rules
          echo "Creating branch protection rules for branch $branch in repo $owner/$repo..."

          curl -X PUT -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$owner/$repo/branches/$branch/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 2
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'

          echo "Branch protection rules applied to branch $branch in repo $owner/$repo."
