name: Add Branch Protection Rules

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name (owner/repo)"
        required: true
      branch:
        description: "Branch name to apply protection"
        required: true
      environment:
        description: "Environment name to apply protection rules"
        required: true

jobs:
  set-environment-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Branch Protection Rules
        env:
          AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Parse inputs
          owner=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f1)
          repo=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f2)
          branch="${{ github.event.inputs.branch }}"
          environment="${{ github.event.inputs.environment }}"

          # Check if the environment exists
          echo "Checking if environment $environment exists..."
          environment_check=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$owner/$repo/environments/$environment)

          if [ "$environment_check" -ne 200 ]; then
            echo "Error: Environment '$environment' does not exist in repository '$repo'. Please create it manually before running this workflow."
            exit 1
          fi

          # Prepare JSON payload
          json_payload=$(cat <<EOF

          # Apply protection rules
          echo "Applying branch protection rules for branch $branch in environment $environment..."
          echo "Payload: $json_payload"

          curl -X PUT -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$owner/$repo/environments/$environment \
            -d "$json_payload"

          echo "Environment-specific protection rules applied to branch $branch in environment $environment"
