name: Add Tag Protection
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern to protect (e.g., v*)'
        required: true
        type: string
      environment:
        description: 'Environment to add tag protection (e.g., Dev)'
        required: true
        type: string

jobs:
  add-tag-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add tag protection
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Use your custom token
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          TAG_PATTERN: ${{ github.event.inputs.tag_pattern }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          # Validate inputs
          if [[ -z "$REPO_NAME" || -z "$TAG_PATTERN" || -z "$ENVIRONMENT" ]]; then
            echo "Error: Missing required inputs."
            exit 1
          fi

          # Add tag protection using GitHub API
          echo "Adding tag protection for repo: $REPO_NAME, tag pattern: $TAG_PATTERN, environment: $ENVIRONMENT"
          curl -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$REPO_NAME/environments/$ENVIRONMENT" \
            -d '{
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

          echo "Tag protection added successfully!"
