name: Tag Protection
on:
  push:
    tags:
      - 'v*' # Only trigger for tags starting with 'v'

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag format
        run: |
          if [[ $GITHUB_REF != refs/tags/v* ]]; then
            echo "$GITHUB_REF"
            echo "Tag does not match the required format (v*)"
            exit 1
          fi
