name: Announcement for Change
run-name: "Announcement for Change # ${{ inputs.change_id }}"
on:
  workflow_dispatch:
    inputs:
      test_email:
        type: boolean
        required: true
        default: true
        description: 'Send a test email to the specified test email'
      change_id:
        type: string
        required: false
        default: 'CHG-123'
        description: 'ID of the change'
      to:
        type: string
        required: true
        description: 'Recipients (comma-separated emails)'   
      bcc:
        type: string
        required: false
        default: ''
        description: 'BCC recipients (comma-separated emails)'     
      change:
        type: string
        required: true
        description: 'Change description'
      change_window:
        type: string
        required: true
        description: 'Time window for the change'   
      impact:
        type: string
        required: true
        description: 'Impact of the change'      
      change_summary:
          type: string
          required: true
          description: 'Summary of the change'
      action_needed:
          type: string
          required: true
          description: 'Actions needed from recipients' 
      note:
          type: string
          required: true
          description: 'Additional notes'    
      
jobs:
  Make-Announcements:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 
        
      - name: Announcement for Change
        id: set-template
        run: |  
            echo "The workflow was triggered by ${{ github.actor }}"
            # Use triple quotes and cat to preserve multiline input
            cat > inputs.txt << 'EOL'
            ${{ inputs.to }}
            EOL
            to=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.change }}
            EOL
            change=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.change_window }}
            EOL
            change_window=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.impact }}
            EOL
            impact=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.change_summary }}
            EOL
            change_summary=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.action_needed }}
            EOL
            action_needed=$(cat inputs.txt)
            
            cat > inputs.txt << 'EOL'
            ${{ inputs.note }}
            EOL
            note=$(cat inputs.txt)
            
            python set-email-change-template.py """$to""" """$change""" """$change_window""" """$impact""" """$change_summary""" """$action_needed""" """$note"""
      
      - name: Send test Mail 
        if: ${{ inputs.test_email == true }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Test- ${{ inputs.change_id }}
          html_body: file://${{ github.workspace }}/email.html
          to: saikiran9487@gmail.com
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: logo.JPG
      
      - name: Send Template Mail 
        if: ${{ inputs.test_email == false }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Test - ${{ inputs.change_id }}
          html_body: file://${{ github.workspace }}/email.html
          to: ${{ inputs.to }}
          from: ${{ secrets.SMTP_USERNAME }}
          bcc: ${{ inputs.bcc }}
          attachments: logo.JPG
