name: Announcement for Change
run-name: "Announcement for Change # ${{ inputs.change_id }}"
on:
  workflow_dispatch:
    inputs:
      test_email:
        type: boolean
        required: true
        default: true
        description: 'Send a test email to the specified test email'
      change_id:
        type: string
        required: false
        default: 'CHG-123'
        description: 'ID of the change'
      to:
        type: string
        required: true
        description: 'Recipients (comma-separated emails)'   
      bcc:
        type: string
        required: false
        default: ''
        description: 'BCC recipients (comma-separated emails)'     
      change:
        type: string
        required: true
        description: 'Change description'
      change_window:
        type: string
        required: true
        description: 'Time window for the change'   
      impact:
        type: string
        required: true
        description: 'Impact of the change. Paste multiline text as is.'      
      change_summary:
          type: string
          required: true
          description: 'Summary of the change. Paste multiline text as is.'
      action_needed:
          type: string
          required: true
          description: 'Actions needed from recipients. Paste multiline text as is.' 
      note:
          type: string
          required: true
          description: 'Additional notes. Paste multiline text as is.'    
      
jobs:
  Make-Announcements:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 
        
      - name: Save inputs to files
        run: |
          echo '${{ inputs.impact }}' > impact.txt
          echo '${{ inputs.change_summary }}' > change_summary.txt
          echo '${{ inputs.action_needed }}' > action_needed.txt
          echo '${{ inputs.note }}' > note.txt
      
      - name: Create Python processor
        run: |
          cat > process_multiline.py << 'EOF'
          import sys
          
          def process_multiline(filename):
              # Read the input file
              with open(filename, "r") as f:
                  content = f.read()
              
              # Replace newlines with <br> tags for HTML
              formatted = content.replace('\n', '<br>')
              
              return formatted
          
          if __name__ == "__main__":
              if len(sys.argv) < 2:
                  print("Usage: python process_multiline.py <filename>")
                  sys.exit(1)
                  
              filename = sys.argv[1]
              result = process_multiline(filename)
              print(result)
          EOF
        
      - name: Process multiline inputs
        id: process-inputs
        run: |
          impact=$(python3 process_multiline.py impact.txt)
          change_summary=$(python3 process_multiline.py change_summary.txt)
          action_needed=$(python3 process_multiline.py action_needed.txt)
          note=$(python3 process_multiline.py note.txt)
          
          echo "impact=$impact" >> $GITHUB_ENV
          echo "change_summary=$change_summary" >> $GITHUB_ENV
          echo "action_needed=$action_needed" >> $GITHUB_ENV
          echo "note=$note" >> $GITHUB_ENV
      
      - name: Announcement for Change
        id: set-template
        run: |  
            echo "The workflow was triggered by ${{ github.actor }}"
            
            python set-email-change-template.py \
              "${{ inputs.to }}" \
              "${{ inputs.change }}" \
              "${{ inputs.change_window }}" \
              "${{ env.impact }}" \
              "${{ env.change_summary }}" \
              "${{ env.action_needed }}" \
              "${{ env.note }}"
      
      - name: Send test Mail 
        if: ${{ inputs.test_email == true }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Platform DevOps Automated Notification - ${{ inputs.change_id }}
          html_body: file://${{ github.workspace }}/email.html
          to: saikiran9487@gmail.com
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: logo.JPG
      
      - name: Send Template Mail 
        if: ${{ inputs.test_email == false }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Platform DevOps Automated Notification - ${{ inputs.change_id }}
          html_body: file://${{ github.workspace }}/email.html
          to: ${{ inputs.to }}
          from: ${{ secrets.SMTP_USERNAME }}
          bcc: ${{ inputs.bcc }}
          attachments: logo.JPG
          
      - name: Github Step Summary
        run: |
          echo "Change: ${{ inputs.change }}" >> $GITHUB_STEP_SUMMARY
          echo "Recipients: ${{ inputs.to }}" >> $GITHUB_STEP_SUMMARY
          echo "Change window: ${{ inputs.change_window }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Clean Workspace
        run: |
          rm -f email.html impact.txt change_summary.txt action_needed.txt note.txt process_multiline.py
          echo "Workspace cleared for run ID ${{ github.run_number }}"
