name: Deploy Tag Rule

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'The name of the repository'
        required: true
        default: ${{ github.repository }}
      tag_pattern:
        description: 'The tag pattern (ref type)'
        required: true
        default: 'v*'  # Default pattern can be all tags starting with "v"
      environment:
        description: 'The environment to deploy the tag'
        required: true
        default: 'production'

jobs:
  add_deployment_rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Deployment Rule for Tag
        run: |
          echo "Creating deployment rule for tag..."
          
          TAG_PATTERN="${{ github.event.inputs.tag_pattern }}"  # Dynamic tag pattern
          ENVIRONMENT="${{ github.event.inputs.environment }}"  # Dynamic environment
          REPO_NAME="${{ github.event.inputs.repo_name }}"  # Dynamic repo name

          # Verify inputs before making the API call
          echo "Using tag pattern: $TAG_PATTERN"
          echo "Using environment: $ENVIRONMENT"
          echo "Using repo name: $REPO_NAME"
          
          # Use curl to make the API request to GitHub
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"ref_type": "tag", "name_pattern": "'"${TAG_PATTERN}"'"}' \
            "https://api.github.com/repos/${REPO_NAME}/environments/${ENVIRONMENT}/deployment-branches-and-tags"
          
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Confirm deployment rule
        run: echo "Deployment rule for tag pattern '${TAG_PATTERN}' has been successfully added to environment '${ENVIRONMENT}'!"
