name: Tag Protection

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Target repository (format: owner/repo)'
        required: true
        type: string
      environment:
        description: 'Environment to apply protection'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern (regex)'
        required: true
        type: string
  push:
    tags:
      - '*'

jobs:
  check-tag:
    # Use the input environment or fall back to repository variable
    environment: ${{ github.event.inputs.environment || vars.TAG_PROTECTION_ENV }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Repository
        run: |
          # Use input repository or fall back to repository variable
          TARGET_REPO="${{ github.event.inputs.repository || vars.PROTECTED_REPOSITORY }}"
          if [ "$TARGET_REPO" != "${{ github.repository }}" ]; then
            echo "Tag protection not configured for this repository"
            exit 0
          fi

      - name: Validate Tag Format
        run: |
          # Use input pattern or fall back to repository variable
          TAG_PATTERN="${{ github.event.inputs.tag_pattern || vars.TAG_PATTERN }}"
          # If still not set, use default pattern
          if [ -z "$TAG_PATTERN" ]; then
            TAG_PATTERN='^(v[0-9]+\.[0-9]+\.[0-9]+|release-[0-9]+\.[0-9]+\.[0-9]+)$'
          fi
          
          if [[ ${{ github.ref_name }} =~ $TAG_PATTERN ]]; then
            echo "Tag format is valid: ${{ github.ref_name }}"
          else
            echo "Invalid tag format: ${{ github.ref_name }}"
            git push origin :refs/tags/${{ github.ref_name }}
            exit 1
          fi

      - name: Protect Tag
        run: |
          # Make the tag immutable using the REST API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/tags/${{ github.ref_name }}/protection" \
            -d '{"enabled": true}'
