name: AAManage Branch Protection

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true
        default: ''
      env:
        description: 'Environment name'
        required: true
        default: ''

jobs:
  manage-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: saikiranrko
          REPO_NAME: ${{ secrets.REPO_NAME }}
          ENV_NAME: ${{ secrets.ENV_NAME }}
        run: python tag4.py
