name: Add Tag Deployment Rule

on:
  workflow_dispatch:

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    steps:
      - name: Add tag deployment rule
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting deployment rule update for environment: Dev"
          
          # Create environment using the correct API path
          echo "Creating/Verifying environment..."
          gh api \
            --method PUT \
            /repos/${{ github.repository }}/environments/Dev \
            --silent || true
          
          # Create deployment rule payload
          TAG_RULE=$(jq -n '{
            "branch_policies": [{
              "name": "refs/tags/release-*",
              "type": "tag"
            }]
          }')
          
          echo "Setting deployment rules..."
          echo "$TAG_RULE"
          
          # Update deployment rules using the correct API path
          RESPONSE=$(gh api \
            --method PUT \
            /repos/${{ github.repository }}/environments/Dev/deployment-branch-policies \
            -H "Accept: application/vnd.github.v3+json" \
            --input - <<< "$TAG_RULE")
          
          if [ $? -eq 0 ]; then
            echo "Successfully updated deployment rules"
            echo "Response: $RESPONSE"
          else
            echo "Error updating deployment rules: $RESPONSE"
            exit 1
          fi
