name: Add Tag Deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name'
        required: true
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    steps:
      - name: Add tag deployment rule
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Using PERSONAL_ACCESS_TOKEN instead of PAT_TOKEN
        run: |
          # Get current deployment branch rules
          RULES=$(gh api \
            repos/${{ github.event.inputs.repository }}/environments/${{ github.event.inputs.environment_name }}/deployment-branch-policies \
            --jq '.branch_policies')
          
          # Create new rule for tags
          NEW_RULE='{"protected_branches":false,"custom_branch_policies":true,"deployment_branch_policy":{"protected_branches":false,"custom_branch_policies":true},"branch_policies":'$RULES'}'
          
          # Add new tag rule
          TAG_RULE='{"name":"refs/tags/*","type":"tag"}'
          
          # Combine existing rules with new tag rule
          if [ "$RULES" == "[]" ]; then
            UPDATED_RULES="[$TAG_RULE]"
          else
            UPDATED_RULES=$(echo $RULES | jq '. + ['$TAG_RULE']')
          fi
          
          # Update environment deployment rules
          gh api \
            --method PUT \
            repos/${{ github.event.inputs.repository }}/environments/${{ github.event.inputs.environment_name }}/deployment-branch-policies \
            -f branch_policies="$UPDATED_RULES"
