name: Add Tag Deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name'
        required: true
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true
      tag_pattern:
        description: 'Tag pattern'
        required: true

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    steps:
      - name: Add tag deployment rule
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Starting deployment rule update for environment: Dev"
          
          # First, create the environment if it doesn't exist
          echo "Creating/Verifying environment..."
          gh api \
            --method PUT \
            repos/saikiranrko/sbc/environments/Dev \
            --silent || true
          
          # Create initial deployment branch policy if none exists
          TAG_RULE=$(jq -n --arg pattern "refs/tags/release-*" '{
            "branch_policies": [{
              "name": $pattern,
              "type": "tag"
            }]
          }')
          
          echo "Setting deployment rules..."
          echo "$TAG_RULE"
          
          # Update environment deployment rules
          RESPONSE=$(gh api \
            --method PUT \
            repos/saikiranrko/sbc/environments/Dev/deployment-branch-policies \
            -H "Accept: application/vnd.github.v3+json" \
            --input - <<< "$TAG_RULE")
          
          if [ $? -eq 0 ]; then
            echo "Successfully updated deployment rules"
            echo "Response: $RESPONSE"
          else
            echo "Error updating deployment rules: $RESPONSE"
            exit 1
          fi
