name: Add Deployment Rule

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to update (e.g., main)'
        required: false
        default: 'main'
      repo_name:
        description: 'Repository to update (e.g., my-repo)'
        required: true
      environment_name:
        description: 'Environment to update (e.g., production)'
        required: true
      tag_pattern:
        description: 'Tag pattern to allow (e.g., v*)'
        required: true

jobs:
  update-deployment-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch the environment configuration
        id: fetch-env
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $PAT" \
               -H "Accept: application/vnd.github+json" \
               -X GET \
               https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}/environments/${{ github.event.inputs.environment_name }} \
               -o environment.json

      - name: Update the environment JSON with the tag rule
        id: update-env
        run: |
          jq --arg tag_pattern "${{ github.event.inputs.tag_pattern }}" \
             --arg branch_name "${{ github.event.inputs.branch_name }}" \
             '.deployment_branch_policy.rules += [{"ref_type": "tag", "pattern": $tag_pattern}]' \
             environment.json > updated_environment.json

      - name: Apply the updated environment configuration
        id: apply-env
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $PAT" \
               -H "Accept: application/vnd.github+json" \
               -X PATCH \
               -d @updated_environment.json \
               https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}/environments/${{ github.event.inputs.environment_name }}

      - name: Verify the update
        id: verify-env
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $PAT" \
               -H "Accept: application/vnd.github+json" \
               -X GET \
               https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}/environments/${{ github.event.inputs.environment_name }} \
               | jq .deployment_branch_policy
