name: Add Tag Protection  
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern to protect (e.g., v*)'
        required: true
        type: string
      environment:
        description: 'Environment to add tag protection (e.g., Dev)'
        required: true
        type: string

jobs:
  add-tag-protection:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install necessary packages (e.g., Axios for API requests)
      - name: Install Axios
        run: |
          npm install axios

      # Step 4: Run a Node.js script to interact with the GitHub API
      - name: Add tag protection pattern using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          TAG_PATTERN: ${{ github.event.inputs.tag_pattern }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          node add_tag_protection.js
