name: Enforce Tag Pattern for Environment Deployments

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name to enforce tag pattern (format: owner/repo)'
        required: true
        type: string
      environment_name:
        description: 'Environment name to enforce tag pattern'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern to enforce (e.g., v*)'
        required: true
        type: string

jobs:
  enforce-tag-pattern:
    if: >
      github.event.deployment.environment == '${{ inputs.environment_name }}' &&
      github.repository == '${{ inputs.repo_name }}'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate tag pattern
        env:
          TAG_PATTERN: ${{ inputs.tag_pattern }}
          DEPLOYMENT_REF: ${{ github.event.deployment.ref }}
        run: |
          # Check if the deployment ref matches the tag pattern
          if [[ ! "$DEPLOYMENT_REF" =~ $TAG_PATTERN ]]; then
            echo "Deployment ref '$DEPLOYMENT_REF' does not match the required tag pattern '$TAG_PATTERN'"
            exit 1
          fi
          echo "Deployment ref '$DEPLOYMENT_REF' matches the required tag pattern '$TAG_PATTERN'"
