name: Add Tag Protection
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern to protect (e.g., v*)'
        required: true
        type: string
      environment:
        description: 'Environment to add tag protection (e.g., Dev)'
        required: true
        type: string

jobs:
  add-tag-protection:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Step 3: Run Python script to add tag protection pattern
      - name: Add tag protection pattern using Selenium
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          TAG_PATTERN: ${{ github.event.inputs.tag_pattern }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          python add_tag_protection.py
