name: Update Environment and Enforce Tag Pattern

on:
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: "Tag pattern to restrict deployments (e.g., 'v*')"
        required: true
        default: "v*"
      environment:
        description: "Environment to update (e.g., 'Dev')"
        required: true
        default: "Dev"
      repository:
        description: "Repository name (e.g., 'saikiranrko/ab')"
        required: true
        default: "saikiranrko/ab"

jobs:
  update-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update environment to allow custom branch policies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ inputs.environment }}
          REPOSITORY: ${{ inputs.repository }}
        run: |
          # Extract owner and repo name from the repository input
          OWNER=$(echo "$REPOSITORY" | cut -d'/' -f1)
          REPO=$(echo "$REPOSITORY" | cut -d'/' -f2)

          # Make API request to update the environment
          curl -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$OWNER/$REPO/environments/$ENVIRONMENT" \
            -d '{
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

          echo "Environment '$ENVIRONMENT' updated to allow custom branch policies."

  enforce-tag-pattern:
    runs-on: ubuntu-latest
    needs: update-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enforce tag pattern for deployments
        env:
          TAG_PATTERN: ${{ inputs.tag_pattern }}
        run: |
          # Check if the ref is a tag and matches the pattern
          if [[ "$GITHUB_REF" != refs/tags/$TAG_PATTERN ]]; then
            echo "Deployment failed: Only tags matching '$TAG_PATTERN' are allowed."
            exit 1
          fi

          echo "Deployment allowed: Tag '$GITHUB_REF' matches pattern '$TAG_PATTERN'."
