name: Configure Tag Protection

on:
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: 'Tag pattern to protect'
        required: true
        default: 'release-*'
      environment:
        description: 'Environment to apply tag protection'
        required: true
        default: 'Dev'
      repository:
        description: 'Owner/Repository to apply tag protection'
        required: true
        default: 'owner/repo'

jobs:
  configure-tag-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create Configuration File
      run: |
        echo "Creating updated_repo_details.json..."
        echo '{ "tag_protection": { "ref_type": "tag", "pattern": "'${{ github.event.inputs.tag_pattern }}'", "environment": "'${{ github.event.inputs.environment }}'" } }' > updated_repo_details.json
        echo "File updated_repo_details.json created."

    - name: Commit and Push Changes Directly to Main
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add updated_repo_details.json
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Added tag protection with pattern ${{ github.event.inputs.tag_pattern }}"
          git push origin main || { echo "Failed to push changes."; exit 1; }
          echo "Changes pushed directly to main branch."
