name: Configure Tag Protection

on:
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: 'Tag pattern to protect'
        required: true
        default: 'release-*'
      environment:
        description: 'Environment to apply tag protection'
        required: true
        default: 'Dev'
      repository:
        description: 'Repository to apply tag protection'
        required: true
        default: 'abc'

jobs:
  configure-tag-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: saikiranrko/${{ github.event.inputs.repository }}
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Push Changes to a New Branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        NEW_BRANCH="tag-protection-${{ github.run_id }}"
        git checkout -b $NEW_BRANCH
        git add updated_repo_details.json
        git commit -m "Added tag protection with pattern ${{ github.event.inputs.tag_pattern }}"
        git push origin $NEW_BRANCH

    - name: Create Pull Request
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        PR_RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/saikiranrko/${{ github.event.inputs.repository }}/pulls \
          -d '{
            "title": "Add tag protection with pattern '${{ github.event.inputs.tag_pattern }}'",
            "head": "tag-protection-'${{ github.run_id }}'",
            "base": "main",
            "body": "This pull request adds tag protection with pattern '${{ github.event.inputs.tag_pattern }}'."
          }')

        PR_NUMBER=$(echo "$PR_RESPONSE" | jq '.number')
        echo "Pull request number: $PR_NUMBER"

    - name: Add Reviewer
      if: success() && steps.create_pr.outputs.PR_NUMBER != 'null'
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/saikiranrko/${{ github.event.inputs.repository }}/pulls/$PR_NUMBER/requested_reviewers \
          -d '{"reviewers": ["REVIEWER_USERNAME"]}'
