name: Enforce Tag Pattern

on:
  # Trigger on manual dispatch with custom inputs
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: 'Tag pattern to protect'
        required: true
        default: 'release-*'
      environment:
        description: 'Environment to apply tag protection'
        required: true
        default: 'Dev'
      repository:
        description: 'Owner/Repository to apply tag protection'
        required: true
        default: 'saikiranrko/abc'

  # Trigger on tag creation
  create:
    tags:
      - "*"

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set Inputs
        id: set-inputs
        run: |
          # Retrieve inputs and set them as environment variables
          echo "Setting tag pattern: ${{ github.event.inputs.tag_pattern }}"
          echo "TAG_PATTERN=${{ github.event.inputs.tag_pattern }}" >> $GITHUB_ENV

          echo "Setting environment: ${{ github.event.inputs.environment }}"
          echo "TARGET_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

          echo "Setting repository: ${{ github.event.inputs.repository }}"
          echo "TARGET_REPO=${{ github.event.inputs.repository }}" >> $GITHUB_ENV

      - name: Validate Tag Name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the created tag name and input values
          TAG_NAME="${GITHUB_REF_NAME}"
          TAG_PATTERN="${TAG_PATTERN}"
          TARGET_ENV="${TARGET_ENV}"
          TARGET_REPO="${TARGET_REPO}"

          echo "Tag created: $TAG_NAME"
          echo "Enforcing pattern: $TAG_PATTERN"
          echo "Applying tag protection in environment: $TARGET_ENV for repository: $TARGET_REPO"

          # Validate the tag name against the pattern
          if [[ ! "$TAG_NAME" =~ $TAG_PATTERN ]]; then
            echo "❌ Invalid tag name: $TAG_NAME"
            echo "The tag must follow the pattern: $TAG_PATTERN"

            # Delete the invalid tag using GitHub API
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/$TARGET_REPO/git/refs/tags/${TAG_NAME}"

            exit 1  # Fail the workflow to notify users
          fi

          echo "✅ Tag $TAG_NAME matches the required pattern and is protected."
