name: Send_Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Test email from GitHub Action'
          body: 'This is a test email sent by GitHub Action.'
          to: 'saikiran9487@gmail.com'
          from: ${{ secrets.SMTP_USERNAME }}
