name: ConfigureTag Protection

on:
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: 'Tag pattern to protect'
        required: true
        default: 'release-*'
      environment:
        description: 'Environment to apply tag protection'
        required: true
        default: 'Dev'
      repository:
        description: 'Owner/Repository to apply tag protection'
        required: true
        default: 'saikiranrko/abc'

jobs:
  configure-tag-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create Configuration File
      run: |
        echo "Creating updated_repo_details.json..."
        echo '{
          "tag_protection": {
            "ref_type": "tag",
            "pattern": "'${{ github.event.inputs.tag_pattern }}'",
            "environment": "'${{ github.event.inputs.environment }}'"
          }
        }' > updated_repo_details.json
        echo "File updated_repo_details.json created."

    - name: Push Changes to a New Branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        NEW_BRANCH="tag-protection-${{ github.run_id }}"
        git checkout -b $NEW_BRANCH
        git add updated_repo_details.json
        git commit -m "Added tag protection with pattern ${{ github.event.inputs.tag_pattern }}"
        git push origin $NEW_BRANCH
        echo "New branch $NEW_BRANCH created and pushed."

    - name: Create Pull Request
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Creating a pull request..."
        PR_RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.event.inputs.repository }}/pulls \
          -d '{
            "title": "Add tag protection with pattern '${{ github.event.inputs.tag_pattern }}'",
            "head": "tag-protection-'${{ github.run_id }}'",
            "base": "main",
            "body": "This pull request adds tag protection with pattern '${{ github.event.inputs.tag_pattern }}'."
          }')

        echo "PR_RESPONSE=$PR_RESPONSE" # Debug the API response
        PR_NUMBER=$(echo "$PR_RESPONSE" | jq '.number')
        echo "Extracted PR_NUMBER=$PR_NUMBER"

        if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
          echo "Error: Pull request number is invalid. Exiting."
          exit 1
        fi

    - name: Add Self as Reviewer
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Adding self as reviewer to the pull request..."
        curl -X POST \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.event.inputs.repository }}/pulls/$PR_NUMBER/requested_reviewers \
          -d '{"reviewers": ["'${{ github.actor }}'"]}'
