name: Configure Tag Protection

on:
  workflow_dispatch:
    inputs:
      tag_pattern:
        description: 'Tag pattern to protect'
        required: true
        default: 'release-*'
      environment:
        description: 'Environment to apply tag protection'
        required: true
        default: 'Dev'
      repository:
        description: 'Repository to apply tag protection'
        required: true
        default: 'saikiranrko/abc'

jobs:
  configure-tag-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Inputs
      id: inputs
      run: |
        echo "Fetching inputs..."
        echo "Branch: ${{ github.event.inputs.branch }}"
        echo "Tag Pattern: ${{ github.event.inputs.tag_pattern }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Repository: ${{ github.event.inputs.repository }}"

    - name: Fetch Repository Details
      id: fetch_repo
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Fetching repository details for ${{ github.event.inputs.repository }}..."
        curl -X GET \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repository }} \
          -o repo_details.json
        echo "Repository details saved to repo_details.json"

    - name: Update Configuration for Tag Protection
      id: update_config
      run: |
        echo "Adding tag protection to repository configuration..."
        REPO_JSON=$(cat repo_details.json)

        # Add custom metadata for tag protection (this is a simulated example)
        echo "$REPO_JSON" | jq \
          '. + {tag_protection: {ref_type: "tag", pattern: "'${{ github.event.inputs.tag_pattern }}'", branch: "'${{ github.event.inputs.branch }}'", environment: "'${{ github.event.inputs.environment }}'"}}' \
          > updated_repo_details.json
        echo "Updated repository configuration saved to updated_repo_details.json."

    - name: Push Changes (Simulated)
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Pushing updated repository details (if supported)..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add updated_repo_details.json
        git commit -m "Added tag protection with pattern ${{ github.event.inputs.tag_pattern }}"
        echo "Changes pushed (simulation)."

    - name: Validate Tag Protection
      run: |
        echo "Validating tag protection for repository ${{ github.event.inputs.repository }}..."
        echo "Branch: ${{ github.event.inputs.branch }}"
        echo "Tag Pattern: ${{ github.event.inputs.tag_pattern }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Validation complete."
