name: Add Tag Deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name to add the tag rule to'
        required: true
        type: string
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern (e.g., "v*" for tags starting with v, "*" for all tags)'
        required: true
        type: string
        default: '*'

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Update environment settings
        run: |
          # Prepare the environment update payload
          echo '{
            "deployment_branch_policy": {
              "protected_branches": false,
              "custom_branch_policies": true
            }
          }' > env_update.json
          
          # Update environment settings
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}" \
            -d @env_update.json
          
          rm env_update.json

      - name: Add deployment rule
        run: |
          # Create deployment rules payload
          echo '{
            "name": "${{ inputs.tag_pattern }}",
            "type": "tag"
          }' > rule.json
          
          echo "Adding deployment rule with payload:"
          cat rule.json
          
          # Add the deployment rule
          HTTP_STATUS=$(curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -o response.txt -w "%{http_code}" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies/branches" \
            -d @rule.json)
          
          echo "Response status: $HTTP_STATUS"
          echo "Response body:"
          cat response.txt
          
          if [[ "$HTTP_STATUS" != "2"* ]]; then
            echo "::error::Failed to add deployment rule. Status code: $HTTP_STATUS"
            exit 1
          fi
          
          echo "Successfully added deployment rule"
          
          # Cleanup
          rm -f rule.json response.txt
