name: Add Tag Deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name to add the tag rule to'
        required: true
        type: string
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern (e.g., "v*" for tags starting with v, "*" for all tags)'
        required: true
        type: string
        default: '*'

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Enable custom branch policies
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Enabling custom branch policies for environment: ${{ inputs.environment_name }} in repository: ${{ inputs.repository }}"
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}" \
            -d '{
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

      - name: Get existing rules
        id: get-rules
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Fetching existing deployment rules for environment: ${{ inputs.environment_name }}"
          RESPONSE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies")
          
          echo "Raw response: $RESPONSE"
          if echo "$RESPONSE" | jq -e --arg pattern "${{ inputs.tag_pattern }}" '.branch_policies[] | select(.name == $pattern and .type == "tag")' > /dev/null; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Add tag rule
        if: env.exists != 'true'
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Adding tag rule: ${{ inputs.tag_pattern }} to environment: ${{ inputs.environment_name }} in repository: ${{ inputs.repository }}"

          API_URL="https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies"
          
          RESPONSE_CODE=$(curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -w "%{http_code}" \
            -o response.json \
            "$API_URL" \
            -d '{
              "name": "${{ inputs.tag_pattern }}",
              "type": "tag"
            }')

          echo "Response code: $RESPONSE_CODE"
          echo "Response body:"
          cat response.json

          if [[ "$RESPONSE_CODE" != "2"* ]]; then
            echo "Failed to add tag rule. Response details:"
            cat response.json
            exit 1
          else
            echo "Successfully added tag rule: ${{ inputs.tag_pattern }}"
          fi

      - name: Verify final configuration
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Verifying final deployment rules configuration for environment: ${{ inputs.environment_name }}"
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies" | jq '.'
