name: Add Tag Deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name to add the tag rule to'
        required: true
        type: string
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern (e.g., "v*" for tags starting with v, "*" for all tags)'
        required: true
        type: string
        default: '*'

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Enable custom branch policies
        run: |
          # First, update environment to enable custom branch policies
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}" \
            -d '{
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

      - name: Get existing rules
        id: get-rules
        run: |
          RESPONSE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies")
          
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
          
          # Check if tag rule already exists
          if echo "$RESPONSE" | jq -e --arg pattern "${{ inputs.tag_pattern }}" '.branch_policies[] | select(.name == $pattern and .type == "tag")' > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Add tag rule
        if: steps.get-rules.outputs.exists != 'true'
        run: |
          # Add new tag rule
          STATUS_CODE=$(curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -w "%{http_code}" \
            -o /dev/null \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies/branches" \
            -d '{
              "name": "${{ inputs.tag_pattern }}",
              "type": "tag"
            }')
          
          if [[ "$STATUS_CODE" != "2"* ]]; then
            echo "Failed to add tag rule. Status code: $STATUS_CODE"
            exit 1
          else
            echo "Successfully added tag rule: ${{ inputs.tag_pattern }}"
          fi

      - name: Verify final configuration
        run: |
          echo "Final deployment rules configuration:"
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}/deployment-branch-policies" | jq '.'
