name: Add Protection and Deploy

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
      type:
        description: 'Type of protection (branch or tag)'
        required: true
        type: choice
        options: [Branch, Tag]
      pattern:
        description: 'Branch or tag pattern to protect (e.g., v* or main)'
        required: true
      environment:
        description: 'Environment name for deployment'
        required: true

jobs:
  add_protection:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Add Protection
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          REPO=${{ github.event.inputs.repo_name }}
          PATTERN=${{ github.event.inputs.pattern }}
          TYPE=${{ github.event.inputs.type }}
          ENV=${{ github.event.inputs.environment }}
          API_URL="https://api.github.com/repos/$REPO/environments/$ENV/deployment-branch-policies"

          EXISTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $API_URL | jq -r \
            ".${TYPE,,}_policies[]? | select(.name == \"$PATTERN\").name")

          if [ "$EXISTS" = "$PATTERN" ]; then
            echo "⚠️ $TYPE pattern '$PATTERN' already exists."
            exit 0
          fi

          curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d "{\"name\": \"$PATTERN\"}" $API_URL && \
            echo "✅ Added $TYPE protection for pattern '$PATTERN'."
