name: Deploy on Tag Push

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for any tag that starts with "v" (e.g., v1.0.0, v2.1.3)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (or your environment, e.g., Python, Java, etc.)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the node version or other necessary environment setup

      - name: Run deployment script (replace with your actual deployment steps)
        run: |
          echo "Deploying application with tag: $GITHUB_REF"
          # Add your deployment commands here (e.g., SSH, GitHub API call, etc.)
          # For example:
          # curl -L -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/deployments -d '{"ref":"$GITHUB_REF"}'
          
      - name: Notify deployment status (optional)
        run: |
          echo "Deployment for tag $GITHUB_REF completed successfully."
