name: ADD Tag Protection Rule

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      environment:
        description: 'Environment name'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern to protect (e.g., v*)'
        required: true
        type: string

jobs:
  add_tag_protection_rule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Add Tag Protection Rule
        run: |
          echo "Repository: ${{ github.event.inputs.repository }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Tag Pattern: ${{ github.event.inputs.tag_pattern }}"
          
          # Validate inputs
          if [[ -z "${{ github.event.inputs.repository }}" || -z "${{ github.event.inputs.environment }}" || -z "${{ github.event.inputs.tag_pattern }}" ]]; then
            echo "Required inputs are missing!"
            exit 1
          fi
          
          # Add the tag protection rule
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.event.inputs.repository }}/tags/protection" \
            -d "{
              \"pattern\": \"${{ github.event.inputs.tag_pattern }}\"
            }"
      
      - name: Verify Tag Protection Rules
        run: |
          echo "Fetching tag protection rules..."
          curl -L \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.event.inputs.repository }}/tags/protection"
