name: Add Tag Protection Rule
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name (owner/repo)"
        required: true
      tag_pattern:
        description: "Tag pattern to protect (e.g., v*)"
        required: true

jobs:
  set-tag-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Tag Protection Rule
        env:
          AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_DEBUG: true
        run: |
          # Parse inputs
          owner=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f1)
          repo=$(echo "${{ github.event.inputs.repo }}" | cut -d'/' -f2)
          tag_pattern="${{ github.event.inputs.tag_pattern }}"
          
          # Debug information
          echo "Owner: $owner"
          echo "Repository: $repo"
          echo "Tag Pattern: $tag_pattern"
          
          # Create tag protection rule
          response=$(curl -X POST \
            -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$owner/$repo/tags/protection" \
            -d "{\"pattern\":\"$tag_pattern\"}")
          
          # Check response
          if echo "$response" | jq -e '.id' > /dev/null; then
            echo "Success! Tag protection rule created:"
            echo "$response" | jq '.'
          else
            echo "Error creating tag protection rule:"
            echo "$response" | jq '.'
            exit 1
          fi

