name: Add Tag Protection Rule
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name (e.g., owner/repo)"
        required: true
      environment_name:
        description: "Environment name"
        required: true
        default: "production"
      tag_pattern:
        description: "Tag pattern (e.g., v*)"
        required: true
        default: "v*"

jobs:
  configure-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_name }}
    
    steps:
      - name: Configure environment deployment rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const [owner, repo] = '${{ github.event.inputs.repository }}'.split('/');
            const environment = '${{ github.event.inputs.environment_name }}';
            const tagPattern = '${{ github.event.inputs.tag_pattern }}';
            
            console.log(`Configuring environment ${environment} for ${owner}/${repo}`);
            
            // Create or update environment with deployment protection
            await github.rest.repos.createOrUpdateEnvironment({
              owner: owner,
              repo: repo,
              environment_name: environment,
              deployment_branch_policy: {
                protected_branches: false,
                custom_branch_policies: true
              }
            });
            
            console.log('Environment configured successfully');
            
            // Add deployment rule for tags
            await github.rest.repos.createDeploymentBranchPolicy({
              owner: owner,
              repo: repo,
              environment_name: environment,
              name: tagPattern,
              ref_type: "tag"
            });
            
            console.log(`Tag protection rule added for pattern: ${tagPattern}`);
