name: Add Tag Protection Rule
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment name"
        required: true
        default: "production"
      tag_pattern:
        description: "Tag pattern (e.g., v*)"
        required: true
        default: "v*"

jobs:
  configure-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure environment deployment rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environment = '${{ github.event.inputs.environment_name }}';
            const tagPattern = '${{ github.event.inputs.tag_pattern }}';
            
            await github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: environment,
              deployment_branch_policy: {
                protected_branches: false,
                custom_branch_policies: true
              }
            });
            
            // Add deployment rule for tags
            await github.rest.repos.createDeploymentBranchPolicy({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: environment,
              name: tagPattern,
              ref_type: "tag"
            });
