name: Add Tag deployment Rule

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name to add the tag rule to'
        required: true
        type: string
      repository:
        description: 'Repository name (format: owner/repo)'
        required: true
        type: string
      tag_pattern:
        description: 'Tag pattern (e.g., "v*" for tags starting with v, "*" for all tags)'
        required: true
        type: string
        default: '*'

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Get current environment settings
        id: get-env
        run: |
          RESPONSE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}")
          echo "current_settings=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Update deployment rules
        run: |
          # Get existing settings
          CURRENT_SETTINGS='${{ steps.get-env.outputs.current_settings }}'
          
          # If no existing settings or error, create initial structure
          if [ "$CURRENT_SETTINGS" == "" ] || [ "$CURRENT_SETTINGS" == "null" ] || [[ "$CURRENT_SETTINGS" == *"Not Found"* ]]; then
            NEW_SETTINGS='{
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              },
              "custom_deployment_rules": [
                {
                  "ref_type": "tag",
                  "pattern": "${{ inputs.tag_pattern }}"
                }
              ]
            }'
          else
            # Add new tag rule to existing settings
            NEW_SETTINGS=$(echo $CURRENT_SETTINGS | jq --arg pattern "${{ inputs.tag_pattern }}" '
              .deployment_branch_policy.custom_branch_policies = true |
              if has("custom_deployment_rules") then
                .custom_deployment_rules += [{"ref_type": "tag", "pattern": $pattern}]
              else
                . + {"custom_deployment_rules": [{"ref_type": "tag", "pattern": $pattern}]}
              end
            ')
          fi
          
          # Update the environment with new settings
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ inputs.repository }}/environments/${{ inputs.environment_name }}" \
            -d "$NEW_SETTINGS"
