name: Dynamic Deployment Rule for Branches

on:
  workflow_dispatch:  # Allows for manual triggering of the workflow with inputs
    inputs:
      branch_pattern:
        description: 'The branch pattern (e.g., "main", "dev", "feature/*")'
        required: true
        default: 'main'
      repo_name:
        description: 'Repository name (e.g., "user/repo")'
        required: true
      environment:
        description: 'Deployment environment (e.g., "production", "staging")'
        required: true
        default: 'production'

jobs:
  add-deployment-rule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "BRANCH_PATTERN=${{ github.event.inputs.branch_pattern }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.event.inputs.repo_name }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Display Variables
        run: |
          echo "Branch Pattern: $BRANCH_PATTERN"
          echo "Repository: $REPO_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Add Deployment Branch Rule using GitHub API
        run: |
          # Use the GitHub API to update the deployment branches for the environment
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d @- https://api.github.com/repos/${{ github.repository }}/environments/$ENVIRONMENT \
            <<EOF
            {
              "deployment_branch_policy": {
                "enabled": true,
                "branches": [
                  "$BRANCH_PATTERN"
                ]
              }
            }
            EOF
