name: Add Tag Protection and Deploy.

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
      tag_pattern:
        description: 'Tag pattern to protect (e.g., v*)'
        required: true
      environment:
        description: 'Environment name for deployment'
        required: true

jobs:
  add_tag_protection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        id: setup
        run: echo "Starting tag protection configuration"

      - name: Add tag protection
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          TAG_PATTERN="${{ github.event.inputs.tag_pattern }}"
          ENVIRONMENT="${{ github.event.inputs.environment }}"

          # Set API URL
          API_URL="https://api.github.com/repos/${REPO_NAME}/environments/${ENVIRONMENT}/deployment-branch-policies"

          # Perform the API call to add tag protection
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $API_URL \
            -d "{
                  \"name\": \"${TAG_PATTERN}\",
                  \"type\": \"tag\"
                }"

      - name: Confirmation
        run: echo "Tag protection has been successfully configured for the repository."
