name: Upload Artifactory Artifact to Azure File Share

on:
  workflow_call:
    inputs:
      artifact_path:
        description: 'Path to the artifact in JFrog Artifactory (e.g., libs-release-local/com/example/app/1.0.0/app-1.0.0.zip)'
        required: true
        type: string
      azure_fileshare_name:
        description: 'Azure file share name (e.g., myshare, production)'
        required: true
        type: string
      azure_fileshare_path:
        description: 'Directory path inside file share (e.g., plugins/v1). Leave empty for root.'
        required: false
        type: string
        default: ''
      overwrite:
        description: 'Whether to overwrite existing files in file share (true/false)'
        required: false
        type: string
        default: 'true'
    secrets:
      AZURE_STORAGE_CONNECTION_STRING:
        description: 'Azure Storage Connection String (preferred for File Share)'
        required: false
      AZURE_STORAGE_ACCOUNT_NAME:
        description: 'Azure Storage Account Name (alternative auth method)'
        required: false
      AZURE_STORAGE_ACCOUNT_KEY:
        description: 'Azure Storage Account Key (alternative auth method)'
        required: false
      AZURE_FILESHARE_SAS_TOKEN_URL:
        description: 'Azure File Share SAS token URL (fallback auth method)'
        required: false
      ARTIFACTORY_USERNAME:
        description: 'JFrog Artifactory username'
        required: true
      ARTIFACTORY_PASSWORD:
        description: 'JFrog Artifactory password'
        required: true

env:
  ARTIFACTORY_URL: "https://unwisely-sweepable-vincent.ngrok-free.dev/artifactory"

jobs:
  upload-artifact-to-fileshare:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact from JFrog Artifactory
        id: download-artifact
        run: |
          echo "=========================================="
          echo "Step 1: Download Artifact from JFrog"
          echo "=========================================="
          echo "Downloading artifact: ${{ inputs.artifact_path }}"
          
          ARTIFACT_FILE=$(basename "${{ inputs.artifact_path }}")
          echo "Artifact filename: $ARTIFACT_FILE"
          echo "Full Artifactory URL: ${ARTIFACTORY_URL}/${{ inputs.artifact_path }}"
          
          curl -f -sS -u "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}" \
            -o "$ARTIFACT_FILE" \
            "${ARTIFACTORY_URL}/${{ inputs.artifact_path }}"
          
          if [ $? -eq 0 ]; then
            echo "✓ Download completed successfully!"
            ls -lh "$ARTIFACT_FILE"
          else
            echo "✗ Download failed!"
            exit 1
          fi
          
          echo "artifact_file=$ARTIFACT_FILE" >> $GITHUB_OUTPUT
      
      - name: Unzip the Artifact
        id: unzip-artifact
        run: |
          echo "=========================================="
          echo "Step 2: Unzip the Artifact"
          echo "=========================================="
          
          ARTIFACT_FILE="${{ steps.download-artifact.outputs.artifact_file }}"
          
          if [[ "$ARTIFACT_FILE" == *.zip ]]; then
            echo "ZIP file detected: $ARTIFACT_FILE"
            
            EXTRACT_DIR="extracted_content"
            mkdir -p "$EXTRACT_DIR"
            
            unzip -o "$ARTIFACT_FILE" -d "$EXTRACT_DIR"
            
            if [ $? -eq 0 ]; then
              echo "✓ Extraction completed successfully!"
              ls -laR "$EXTRACT_DIR"
              
              echo "extracted_path=$(pwd)/$EXTRACT_DIR" >> $GITHUB_OUTPUT
              echo "is_zip=true" >> $GITHUB_OUTPUT
            else
              echo "✗ Extraction failed!"
              exit 1
            fi
          else
            echo "Not a ZIP file - will upload as single file"
            echo "extracted_path=" >> $GITHUB_OUTPUT
            echo "is_zip=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Prepare upload source
        id: prepare-upload
        run: |
          echo "=========================================="
          echo "Step 3: Prepare Upload Source"
          echo "=========================================="
          
          IS_ZIP="${{ steps.unzip-artifact.outputs.is_zip }}"
          ARTIFACT_FILE="${{ steps.download-artifact.outputs.artifact_file }}"
          EXTRACTED_PATH="${{ steps.unzip-artifact.outputs.extracted_path }}"
          
          if [ "$IS_ZIP" == "true" ]; then
            UPLOAD_SOURCE="$EXTRACTED_PATH"
          else
            UPLOAD_SOURCE="$ARTIFACT_FILE"
          fi
          
          echo "upload_source=$UPLOAD_SOURCE" >> $GITHUB_OUTPUT
      
      - name: Determine authentication method
        id: auth-method
        run: |
          echo "=========================================="
          echo "Determining Authentication Method"
          echo "=========================================="
          
          if [ ! -z "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" ]; then
            echo "Using: Connection String authentication (RECOMMENDED for File Share)"
            echo "auth_method=connection_string" >> $GITHUB_OUTPUT
          elif [ ! -z "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" ] && [ ! -z "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" ]; then
            echo "Using: Account Name + Key authentication"
            echo "auth_method=account_key" >> $GITHUB_OUTPUT
          elif [ ! -z "${{ secrets.AZURE_FILESHARE_SAS_TOKEN_URL }}" ]; then
            echo "Using: SAS Token authentication"
            echo "auth_method=sas_token" >> $GITHUB_OUTPUT
          else
            echo "✗ No valid authentication method found!"
            echo "Please provide one of:"
            echo "  - AZURE_STORAGE_CONNECTION_STRING, or"
            echo "  - AZURE_STORAGE_ACCOUNT_NAME + AZURE_STORAGE_ACCOUNT_KEY, or"
            echo "  - AZURE_FILESHARE_SAS_TOKEN_URL"
            exit 1
          fi
      
      - name: Install azcopy
        run: |
          echo "Installing azcopy..."
          wget -q https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
          tar -xzf azcopy.tar.gz --strip-components=1
          sudo mv azcopy /usr/local/bin/
          sudo chmod +x /usr/local/bin/azcopy
          azcopy --version
      
      - name: Upload to Azure File Share
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          echo "=========================================="
          echo "Step 4: Upload to Azure File Share"
          echo "=========================================="
          
          UPLOAD_SOURCE="${{ steps.prepare-upload.outputs.upload_source }}"
          IS_ZIP="${{ steps.unzip-artifact.outputs.is_zip }}"
          FILESHARE_NAME="${{ inputs.azure_fileshare_name }}"
          FILESHARE_PATH="${{ inputs.azure_fileshare_path }}"
          OVERWRITE="${{ inputs.overwrite }}"
          AUTH_METHOD="${{ steps.auth-method.outputs.auth_method }}"
          
          echo "Upload source: $UPLOAD_SOURCE"
          echo "File share name: $FILESHARE_NAME"
          echo "File share path: ${FILESHARE_PATH:-'(root)'}"
          echo "Overwrite existing: $OVERWRITE"
          echo "Authentication: $AUTH_METHOD"
          echo ""
          
          # Build destination URL based on auth method
          if [ "$AUTH_METHOD" == "connection_string" ]; then
            # Extract account name and key from connection string
            ACCOUNT_NAME=$(echo "$AZURE_STORAGE_CONNECTION_STRING" | grep -oP 'AccountName=\K[^;]*')
            ACCOUNT_KEY=$(echo "$AZURE_STORAGE_CONNECTION_STRING" | grep -oP 'AccountKey=\K[^;]*')
            
            # Export for azcopy to use
            export AZURE_STORAGE_ACCOUNT="$ACCOUNT_NAME"
            export AZURE_STORAGE_KEY="$ACCOUNT_KEY"
            
            BASE_URL="https://${ACCOUNT_NAME}.file.core.windows.net/${FILESHARE_NAME}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              DEST_URL="$BASE_URL"
            else
              DEST_URL="$BASE_URL/$FILESHARE_PATH"
            fi
            
            echo "Destination URL: $DEST_URL (using connection string auth)"
            
          elif [ "$AUTH_METHOD" == "account_key" ]; then
            # Export for azcopy to use
            export AZURE_STORAGE_ACCOUNT="$AZURE_STORAGE_ACCOUNT"
            export AZURE_STORAGE_KEY="$AZURE_STORAGE_KEY"
            
            BASE_URL="https://${AZURE_STORAGE_ACCOUNT}.file.core.windows.net/${FILESHARE_NAME}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              DEST_URL="$BASE_URL"
            else
              DEST_URL="$BASE_URL/$FILESHARE_PATH"
            fi
            
            echo "Destination URL: $DEST_URL (using account key auth)"
            
          else  # SAS Token
            BASE_URL="${{ secrets.AZURE_FILESHARE_SAS_TOKEN_URL }}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              DEST_URL="$BASE_URL"
            else
              URL_WITHOUT_QUERY="${BASE_URL%%\?*}"
              QUERY_STRING="${BASE_URL#*\?}"
              DEST_URL="${URL_WITHOUT_QUERY}/${FILESHARE_PATH}?${QUERY_STRING}"
            fi
            
            echo "Destination URL: <masked> (using SAS token auth)"
          fi
          
          echo ""
          
          # Upload based on content type
          if [ "$IS_ZIP" == "true" ]; then
            echo "Uploading directory contents recursively..."
            azcopy cp "$UPLOAD_SOURCE/*" "$DEST_URL" \
              --recursive=true \
              --overwrite=$OVERWRITE
          else
            echo "Uploading single file..."
            azcopy cp "$UPLOAD_SOURCE" "$DEST_URL/" \
              --overwrite=$OVERWRITE
          fi
          
          if [ $? -eq 0 ]; then
            echo ""
            echo "✓ Upload completed successfully!"
          else
            echo ""
            echo "✗ Upload failed!"
            exit 1
          fi
      
      - name: Verify upload and list file share contents
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          echo "=========================================="
          echo "Verification: List File Share Contents"
          echo "=========================================="
          
          FILESHARE_NAME="${{ inputs.azure_fileshare_name }}"
          FILESHARE_PATH="${{ inputs.azure_fileshare_path }}"
          AUTH_METHOD="${{ steps.auth-method.outputs.auth_method }}"
          
          # Build list URL based on auth method and export credentials
          if [ "$AUTH_METHOD" == "connection_string" ]; then
            # Extract account name and key from connection string
            ACCOUNT_NAME=$(echo "$AZURE_STORAGE_CONNECTION_STRING" | grep -oP 'AccountName=\K[^;]*')
            ACCOUNT_KEY=$(echo "$AZURE_STORAGE_CONNECTION_STRING" | grep -oP 'AccountKey=\K[^;]*')
            
            # Export for azcopy to use
            export AZURE_STORAGE_ACCOUNT="$ACCOUNT_NAME"
            export AZURE_STORAGE_KEY="$ACCOUNT_KEY"
            
            BASE_URL="https://${ACCOUNT_NAME}.file.core.windows.net/${FILESHARE_NAME}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              LIST_URL="$BASE_URL"
            else
              LIST_URL="$BASE_URL/$FILESHARE_PATH"
            fi
            
          elif [ "$AUTH_METHOD" == "account_key" ]; then
            # Export for azcopy to use
            export AZURE_STORAGE_ACCOUNT="$AZURE_STORAGE_ACCOUNT"
            export AZURE_STORAGE_KEY="$AZURE_STORAGE_KEY"
            
            BASE_URL="https://${AZURE_STORAGE_ACCOUNT}.file.core.windows.net/${FILESHARE_NAME}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              LIST_URL="$BASE_URL"
            else
              LIST_URL="$BASE_URL/$FILESHARE_PATH"
            fi
            
          else  # SAS Token
            BASE_URL="${{ secrets.AZURE_FILESHARE_SAS_TOKEN_URL }}"
            
            if [ -z "$FILESHARE_PATH" ]; then
              LIST_URL="$BASE_URL"
            else
              URL_WITHOUT_QUERY="${BASE_URL%%\?*}"
              QUERY_STRING="${BASE_URL#*\?}"
              LIST_URL="${URL_WITHOUT_QUERY}/${FILESHARE_PATH}?${QUERY_STRING}"
            fi
          fi
          
          echo "Listing contents at: ${FILESHARE_PATH:-'root'}"
          azcopy list "$LIST_URL"
